### PR TITLE
Angular frontend for the adf-widget-registry

### PR DESCRIPTION
**Pull request by ivan-saorin**
I just added a brand new frontend for the registry. I would like you have a look at it and eventually merge it to the master.

Ivan

schermata del 2015-07-15 00 11 20

### CODE REVIEW

**Comment by sdorra** [comment]
This is pretty awesome. Thanks.

**Comment by ivan-saorin** [comment]
You are welcome. :)

**Comment by sdorra** [comment]
@ivan-saorin the header seems too big on mobile devices. Do you know how to fix it?

I've modified the build a little bit, to serve the api as part of gulp serve. I also moved the client sources to a client directory and the server sources to a server directory.

**Comment by ivan-saorin** [comment]
It looks good to me. I will look at the big header asap.

2015-07-15 21:10 GMT+02:00 Sebastian Sdorra notifications@github.com:

**Pull request merged**
