### PR TITLE
Changes needed for showcase.md files

### PR DESCRIPTION
**Pull request by ivan-saorin**

### CODE REVIEW

**Comment by sdorra** [comment]
I get an reference error, if a try to build the registry with the default gulp task.

``` text
ReferenceError: debug is not defined
    at Gulp.<anonymous> (/Users/sdorra/Desktop/adf-widget-registry/gulp/build.js:48:11)
    at module.exports (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/sdorra/Desktop/adf-widget-registry/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
```

**Comment by ivan-saorin** [comment]
Ok. I will take a look at it tomorrow morning. sorry.

Inviato da iPad

**Comment by ivan-saorin** [comment]
Should be fixed now. Let me know.

**Comment by sdorra** [comment]
Thanks

**Pull request merged**
